# Generated by Django 3.0.7 on 2020-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
