# Generated by Django 3.0.7 on 2020-06-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapi', '0003_auto_20200626_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapi.Programmer'),
            preserve_default=False,
        ),
    ]
